# -*- coding: utf-8 -*-
"""House_price_prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIk2Na1jotLBWt_E7B4ja_Hv77rHm6A5

***House Price Prediction Model***
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as mpt
import seaborn as sns
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics

"""***inserting house price data from an existing csv file ***"""

house_price_dataframe=pd.read_csv("/content/boston_house_prices.csv")

house_price_dataframe.head()

house_price_dataframe.shape

house_price_dataframe.isnull().sum()

house_price_dataframe.describe()

correlation=house_price_dataframe.corr()

mpt.figure(figsize=(10,10))
sns.heatmap(correlation,cbar=True,square=True,fmt='.2f',annot=True,annot_kws={'size':8},cmap='green')

X=house_price_dataframe.drop(['MEDV'],axis=1)
Y=house_price_dataframe['MEDV']

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

model=XGBRegressor()

model.fit(x_train,y_train)

train_data_prediction=model.predict(x_train)

s1=metrics.r2_score(y_train,train_data_prediction)
s2=metrics.mean_absolute_error(y_train,train_data_prediction)

print("R2 score",s1)
print("MAE score",s2)

test_data_prediction=model.predict(x_test)

s1=metrics.r2_score(y_test,test_data_prediction)
s2=metrics.mean_absolute_error(y_test,test_data_prediction)

print("R2 score",s1)
print("MAE score",s2)

mpt.scatter(y_train,train_data_prediction)
mpt.xlabel("Actual Price")
mpt.ylabel("Predicted Price")
mpt.title("Actual Price vs Predicted Price")
mpt.show()

